/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Skeptical_Tech
 */
public class InfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        BasicPanel = new javax.swing.JPanel();
        NamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        VersionPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        PGMVerPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        ObjectivePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        AuthorPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ContributorPanel = new javax.swing.JPanel();
        RulesPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(700, 500));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        BasicPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Name:");
        NamePanel.add(jLabel1);

        jTextField1.setColumns(28);
        jTextField1.setText("jTextField1");
        jTextField1.setToolTipText("The name of the map.");
        jTextField1.setMinimumSize(new java.awt.Dimension(150, 22));
        NamePanel.add(jTextField1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.ipady = 5;
        BasicPanel.add(NamePanel, gridBagConstraints);

        jLabel2.setText("Version:");
        VersionPanel.add(jLabel2);

        jTextField2.setText("jTextField1");
        jTextField2.setToolTipText("The name of the map.");
        VersionPanel.add(jTextField2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        BasicPanel.add(VersionPanel, gridBagConstraints);

        PGMVerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("PGM Version:");
        PGMVerPanel.add(jLabel3);

        jTextField3.setColumns(4);
        jTextField3.setText("1.3.0");
        jTextField3.setToolTipText("The name of the map.");
        PGMVerPanel.add(jTextField3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        BasicPanel.add(PGMVerPanel, gridBagConstraints);

        ObjectivePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Objective:");
        ObjectivePanel.add(jLabel4);

        jTextArea1.setColumns(35);
        jTextArea1.setRows(2);
        jScrollPane1.setViewportView(jTextArea1);

        ObjectivePanel.add(jScrollPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        BasicPanel.add(ObjectivePanel, gridBagConstraints);

        add(BasicPanel);

        AuthorPanel.setLayout(new java.awt.GridBagLayout());

        jLabel5.setText("Authors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        AuthorPanel.add(jLabel5, gridBagConstraints);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setVisibleRowCount(5);
        jScrollPane2.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        AuthorPanel.add(jScrollPane2, gridBagConstraints);

        jTextField4.setText("jTextField4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        AuthorPanel.add(jTextField4, gridBagConstraints);

        jButton1.setText("jButton1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        AuthorPanel.add(jButton1, gridBagConstraints);

        jButton2.setText("jButton2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        AuthorPanel.add(jButton2, gridBagConstraints);

        add(AuthorPanel);
        add(ContributorPanel);
        add(RulesPanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AuthorPanel;
    private javax.swing.JPanel BasicPanel;
    private javax.swing.JPanel ContributorPanel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JPanel ObjectivePanel;
    private javax.swing.JPanel PGMVerPanel;
    private javax.swing.JPanel RulesPanel;
    private javax.swing.JPanel VersionPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
